name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18] # Specify supported Node.js versions

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Install Playwright browsers
    - name: Install Playwright browsers
      run: npx playwright install

    # Step 5: Run tests
    - name: Run Playwright Tests
      run: npx playwright test
      env:
        CI: true # Ensures that Playwright runs in headless mode for CI

    # Step 6: Upload test results (optional)
    - name: Archive test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-test-results
        path: playwright-report/
